version: 2.1

parameters:
  go:
    type: string
    default: 1.17.2
orbs:
  win: circleci/windows@2.4.1

jobs:
  test-linux:
    docker:
      - image: cimg/go:<< parameters.go >>
    steps:
      - checkout
      - run:
          name: test
          command: |
            sudo apt-get update && sudo apt-get install -y ca-certificates
            go test -failfast --covermode=atomic -race ./...

  test-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: test
          command: |
            go test -failfast --covermode=atomic -race ./...

  test-macos:
    executor:
      name: macos
      xcode: 11.4.1
    environment:
      GOPATH: /Users/distiller/go
      PATH: /Users/distiller/go/bin:/usr/local/go/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    steps:
      - checkout
      - run:
          name: install
          command: |
            curl -sSL https://golang.org/dl/go<< parameters.go >>.darwin-amd64.tar.gz | sudo tar -xzf - -C /Users/distiller/go
            sudo chown ${USER}:admin /Users/distiller/go/go
      - run:
          name: test
          command: |
            go test -failfast --covermode=atomic -race ./...

  lint:
    docker:
      - image: cimg/go:<< parameters.go >>
    steps:
      - checkout
      - run:
          name: downloads
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - run:
          name: lint
          command: |
            golangci-lint run ./...

workflows:
  main:
    jobs:
      - test-linux
      - test-windows
      - test-macos
      - lint
